services:
  - type: web
    name: lk-stroymaterials
    runtime: python
    region: frankfurt
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
      python deploy_script.py
    startCommand: gunicorn lk_clone.wsgi:application  # ← ВАЖНО!
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: lkdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DJANGO_ENV
        value: production
      - key: ALLOWED_HOSTS
        value: ".onrender.com"

databases:
  - name: lkdb
    plan: free
    databaseName: your-db-name
    user: lk_useryourdb_ctsh_user